# Automated EDA (Task 2b).
# In Task 2a I explored the data by running SQL queries one by one.
# This script automates that process:
#   1. pulls the two main tables from Snowflake (pre-aggregated in SQL),
#   2. profiles every dataframe with one reusable function,
#   3. saves a markdown report + charts into analysis/output/.
# Re-running the script regenerates everything, so the EDA is
# repeatable instead of manual.

from datetime import datetime
from pathlib import Path

import matplotlib
matplotlib.use("Agg")  # render charts straight to files, no GUI needed
import matplotlib.pyplot as plt

from sf_connect import get_connection, fetch_df

OUTPUT_DIR = Path(__file__).resolve().parent / "output"
OUTPUT_DIR.mkdir(exist_ok=True)

# --- Queries -------------------------------------------------------
# JHU is huge (millions of province-level rows), so the aggregation
# down to country level happens inside Snowflake. Pandas only
# receives the compact result (~220k rows) instead of the raw table.

JHU_QUERY = """
SELECT COUNTRY_REGION,
       DATE,
       SUM(IFF(CASE_TYPE = 'Confirmed', CASES, 0)) AS CUM_CONFIRMED,
       SUM(IFF(CASE_TYPE = 'Deaths',    CASES, 0)) AS CUM_DEATHS
FROM JHU_COVID_19
WHERE CASE_TYPE IN ('Confirmed', 'Deaths')
GROUP BY COUNTRY_REGION, DATE
ORDER BY COUNTRY_REGION, DATE
"""

ECDC_QUERY = """
SELECT COUNTRY_REGION, DATE, CASES, DEATHS, POPULATION
FROM ECDC_GLOBAL
"""


def profile_dataframe(df, name, lines):
    """Append a standard profile of one dataframe to the report.

    Same checks for any table: shape, duplicates, column types,
    missing values, date coverage, negative values, numeric stats.
    This function is the 'automation' answer of Task 2 - point it
    at any dataframe and it produces the same quality report.
    """
    lines.append(f"\n## Profile: {name}\n")
    lines.append(f"- Shape: {len(df):,} rows x {df.shape[1]} columns")
    lines.append(f"- Fully duplicated rows: {df.duplicated().sum():,}")

    lines.append("\n**Column types**\n")
    for col in df.columns:
        lines.append(f"- `{col}`: {df[col].dtype}")

    lines.append("\n**Missing values**\n")
    na = df.isna().sum()
    if na.sum() == 0:
        lines.append("- none")
    else:
        for col, n in na[na > 0].items():
            lines.append(f"- `{col}`: {n:,} ({n / len(df):.2%})")

    for col in df.select_dtypes("datetime").columns:
        lines.append(
            f"\n**Date coverage of `{col}`:** "
            f"{df[col].min().date()} -> {df[col].max().date()}"
        )

    lines.append("\n**Negative values in numeric columns**\n")
    num_cols = df.select_dtypes("number").columns
    negatives = [
        f"- `{c}`: {int((df[c] < 0).sum()):,} rows"
        for c in num_cols
        if (df[c] < 0).sum() > 0
    ]
    lines.extend(negatives if negatives else ["- none"])

    lines.append("\n**Numeric summary**\n")
    if len(num_cols) > 0:
        lines.append("```")
        lines.append(df[num_cols].describe().round(2).to_string())
        lines.append("```")
    else:
        lines.append("- No numeric columns found to summarize.")


def main():
    conn = get_connection()
    try:
        print("Pulling JHU (aggregated to country level)...")
        jhu = fetch_df(conn, JHU_QUERY)
        print(f"  -> {len(jhu):,} rows")
        print("Pulling ECDC...")
        ecdc = fetch_df(conn, ECDC_QUERY)
        print(f"  -> {len(ecdc):,} rows")
    finally:
        conn.close()

    jhu = jhu.sort_values(["COUNTRY_REGION", "DATE"])
    jhu["NEW_CONFIRMED"] = jhu.groupby("COUNTRY_REGION")["CUM_CONFIRMED"].diff()
    jhu["NEW_DEATHS"] = jhu.groupby("COUNTRY_REGION")["CUM_DEATHS"].diff()

    lines = [
        "# Automated EDA Report",
        f"\nGenerated by auto_eda.py on {datetime.now():%Y-%m-%d %H:%M}",
    ]
    profile_dataframe(jhu, "JHU_COVID_19 (country level)", lines)
    profile_dataframe(ecdc, "ECDC_GLOBAL", lines)

    global_daily = jhu.groupby("DATE")["NEW_CONFIRMED"].sum().rolling(7).mean()
    plt.figure(figsize=(10, 5))
    global_daily.plot()
    plt.title("Global daily new confirmed cases (7-day average)")
    plt.ylabel("cases per day")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "global_daily_cases.png", dpi=150)
    plt.close()

    top10 = (
        jhu.groupby("COUNTRY_REGION")["CUM_CONFIRMED"]
        .max()
        .sort_values(ascending=False)
        .head(10)
    )
    plt.figure(figsize=(10, 5))
    top10.sort_values().plot.barh()
    plt.title("Top 10 countries by total confirmed cases (JHU)")
    plt.xlabel("total confirmed cases")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "top10_countries.png", dpi=150)
    plt.close()

    global_deaths = jhu.groupby("DATE")["NEW_DEATHS"].sum().rolling(7).mean()
    plt.figure(figsize=(10, 5))
    global_deaths.plot(color="firebrick")
    plt.title("Global daily deaths (7-day average)")
    plt.ylabel("deaths per day")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / "global_daily_deaths.png", dpi=150)
    plt.close()

    (OUTPUT_DIR / "eda_report.md").write_text("\n".join(lines))
    print(f"\nDone! Report and 3 charts saved to: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()