USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS BOOTCAMP_RM
  WITH CREDIT_QUOTA = 5
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 95 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER ACCOUNT SET RESOURCE_MONITOR = BOOTCAMP_RM;
SHOW RESOURCE MONITORS;

SELECT CURRENT_USER();

ALTER USER SENNURBASCETIN SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzylmmtslrs/g9Ub4UjvHXGX6mJsnKM8k+QNcX4udVnd3goYXcKNck6iG2waqkrMIdI9wpkU5o7mxh0dwZKsOLC7hbGucdfwrzi5TMkvIfaEAMXAzq1puULRzOpOaNG++e07C/NPjiIC6L9bfau18p6bhamq1Tq7hHCA2GkA5Lcris4Nwm6QfQrNsXYxN9hcz+Qo3kFPjgCWilbvltIpxkwAQv13Q79H8dLUfjRDNjDbCGnmfpbCg2AjtkcIk20YqwuR+MCRgF75rmWcWdJkff0taySTMuymFA2A9JvuGOx7t3KVFUF6yLdbA4wMfS1wV7MGyZpC0MCWStgk9RIDV/QIDAQAB';

DESC USER SENNURBASCETIN;